default_install_hook_types: [pre-commit, commit-msg]
default_language_version:
    python: python3.13
default_stages: [pre-commit, pre-merge-commit, manual]

repos:
    - repo: https://github.com/tsvikas/sync-with-uv
      rev: v0.5.0
      hooks:
        - id: sync-with-uv

    - repo: https://github.com/codespell-project/codespell
      rev: v2.4.1
      hooks:
        - id: codespell

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.10
      hooks:
        - id: actionlint
          additional_dependencies: [github.com/wasilibs/go-shellcheck/cmd/shellcheck@latest]  # yamllint disable-line rule:key-ordering
          args: [-pyflakes=]

    - repo: https://github.com/dotenv-linter/dotenv-linter
      rev: v4.0.0
      hooks:
        - id: dotenv-linter
          args: [fix, --no-backup]

    - repo: https://github.com/hadolint/hadolint
      rev: v2.14.0
      hooks:
        - id: hadolint-docker

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.38.0
      hooks:
        - id: yamllint
          args: [--strict]

    - repo: https://github.com/renovatebot/pre-commit-hooks
      rev: 42.84.0
      hooks:
        - id: renovate-config-validator
          args: [--strict]
          stages: [manual]

    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.36.0
      hooks:
        - id: check-jsonschema
          args: [--schemafile, 'https://json.schemastore.org/yamllint.json']  # yamllint disable-line rule:quoted-strings
          files: ^\.yamllint\.yaml$  # yamllint disable-line rule:key-ordering
          name: Check yamllint configuration file
          types: [yaml]

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
        - id: gitlint
        - id: gitlint-ci

    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.30.0
      hooks:
        - id: gitleaks
          language_version: ">=1.25.4"

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        - id: check-illegal-windows-names
        - id: check-shebang-scripts-are-executable
        - id: check-vcs-permalinks
        - id: destroyed-symlinks
        - id: check-case-conflict
        - id: name-tests-test
          args: [--pytest-test-first]
          files: (?:^|\/)tests\/(?:[^\/]+\/)*(?!_)[^\/]+\.py$  # yamllint disable-line rule:key-ordering
        - id: pretty-format-json
          args: [--autofix, --indent, "4"]

    - repo: builtin
      hooks:
        - id: check-added-large-files
        - id: trailing-whitespace
        - id: check-executables-have-shebangs
        - id: check-json
        - id: check-toml
        - id: check-yaml
        - id: end-of-file-fixer
        - id: check-xml
        - id: check-symlinks
        - id: check-merge-conflict
        - id: mixed-line-ending
          args: [--fix=lf]
        - id: detect-private-key
        - id: fix-byte-order-marker
          args: [-h]

    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.16.0
      hooks:
        - id: pretty-format-ini
          args: [--autofix]

    - repo: https://github.com/tombi-toml/tombi-pre-commit
      rev: v0.7.22
      hooks:
        - id: tombi-format
        - id: tombi-lint

    - repo: https://github.com/astral-sh/uv-pre-commit
      rev: 0.9.26
      hooks:
        - id: uv-lock
          always_run: true

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.14.13
      hooks:
        - id: ruff-check
          args: [--fix]
        - id: ruff-format

    - repo: https://github.com/google/yamlfmt
      rev: v0.21.0
      hooks:
        - entry: yamlfmt
          id: yamlfmt
          pass_filenames: true
          types: [yaml]
