default_install_hook_types: [pre-commit, commit-msg]
default_language_version:
    python: python3.13
default_stages: [pre-commit, pre-merge-commit, manual]

repos:
    - repo: https://github.com/hadolint/hadolint
      rev: v2.14.0
      hooks:
        - id: hadolint-docker

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.37.1
      hooks:
        - id: yamllint
          args: [--strict]

    - repo: https://github.com/renovatebot/pre-commit-hooks
      rev: 42.17.1
      hooks:
        - id: renovate-config-validator
          args: [--strict]
          stages: [manual]

    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.35.0
      hooks:
        - id: check-github-workflows

        - id: check-jsonschema
          args: [--schemafile, 'https://json.schemastore.org/yamllint.json']  # yamllint disable-line rule:quoted-strings
          files: ^\.yamllint\.yaml$  # yamllint disable-line rule:key-ordering
          name: Check yamllint configuration file
          types: [yaml]

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
        - id: gitlint
        - id: gitlint-ci

    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.29.1
      hooks:
        - id: gitleaks

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        - id: check-added-large-files
        - id: trailing-whitespace
        - id: check-executables-have-shebangs
        - id: check-illegal-windows-names
        - id: check-shebang-scripts-are-executable
        - id: check-json
        - id: check-xml
        - id: check-symlinks
        - id: check-merge-conflict
        - id: check-vcs-permalinks
        - id: destroyed-symlinks
        - id: mixed-line-ending
          args: [--fix=lf]
        - id: check-case-conflict
        - id: detect-private-key
        - id: fix-byte-order-marker
          args: [-h]
        - id: name-tests-test
          args: [--pytest-test-first]
        - id: pretty-format-json
          args: [--autofix, --indent, "4"]

    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.15.0
      hooks:
        - id: pretty-format-ini
          args: [--autofix]

    - repo: https://github.com/tombi-toml/tombi-pre-commit
      rev: v0.6.52
      hooks:
        - id: tombi-format
        - id: tombi-lint

    - repo: https://github.com/astral-sh/uv-pre-commit
      rev: 0.9.10
      hooks:
        - id: uv-lock
          always_run: true

    - repo: local
      hooks:
        - id: ruff-check
          args: [--fix]
          description: Run 'ruff check' for extremely fast Python linting  # yamllint disable-line rule:key-ordering
          entry: ruff check --force-exclude  # yamllint disable-line rule:key-ordering
          language: python
          minimum_pre_commit_version: 2.9.2
          name: ruff check
          require_serial: true
          types_or: [python, pyi]

        - id: ruff-format
          description: Run 'ruff format' for extremely fast Python formatting  # yamllint disable-line rule:key-ordering
          entry: ruff format --force-exclude  # yamllint disable-line rule:key-ordering
          language: python
          minimum_pre_commit_version: 2.9.2
          name: ruff format
          require_serial: true
          types_or: [python, pyi]

    - repo: https://github.com/google/yamlfmt
      rev: v0.20.0
      hooks:
        - entry: yamlfmt
          id: yamlfmt
          pass_filenames: true
          types: [yaml]
